[package]
name = "rust-swf-fixed"
version = "0.1.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
edition = "2018"

[dependencies]
serde = "^1.0.80"

[dev-dependencies]
serde_json = "^1.0.32"
