[package]
name = "swf-fixed"
version = "0.1.0"
description = "SWF fixed-point numbers for Rust"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[dependencies]
serde = "^1.0.80"

[dev-dependencies]
serde_json = "^1.0.32"
