[package]
name = "swf-fixed"
version = "0.1.0"
description = "Fixed point numbers for SWF"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
edition = "2018"
license = "MIT"

[dependencies]
serde = "^1.0.80"

[dev-dependencies]
serde_json = "^1.0.32"
